# BungeeWeb Configuration File

# Server settings
server:

  # Port to run the server on
  port: 8080

  # Amount of time in seconds between status checks
  # Set to -1 to disable all graphing
  statscheck: 60

  # Default language to use, loaded from the "lang" directory.
  language: en

  # Amount of days that records will be kept for
  logsdays: 30
  statsdays: 30

  # Amount of minutes between purges
  purge: 10

  # Whether page transitions should be disabled
  disabletransitions: false

# MySQL details
database:
  host: 127.0.0.1
  port: 3306
  user: bungeeweb
  pass: password
  db: bungeeweb
  prefix: bungeeweb_

# Logged items
log:
  chat: true
  command: true
  join: true
  quit: true
  kick: true
  serverchange: true

# Graphed items
stats:
  playercount: true
  maxplayers: true
  activity: true